[features]
seeds = false
[programs.devnet]
candy_machine = "5wVWmdqBedvBgnjeSA5zWKoD9pa6N4GY2Q3bgZMQmAEs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/nkt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
