[features]
seeds = false
[programs.devnet]
candy_machine = "HhyVsqnJexHUtyv8QKEq7J8i8wxLc14xJQbb9Sw4G3ic"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/nkt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
